### ISSUE TITLE
The comments are hard to read when "highlight_line" is set to true in Packages/User/Preferences.sublime-settings

### ISSUE THREAD

**Issue by rwols** [facelessuser/sublime-dracula-scheme#2]
See screenshot

<img width="586" alt="image" src="https://user-images.githubusercontent.com/2431823/97915323-96883f00-1d51-11eb-8bf0-df6850d7c036.png">

**Comment by facelessuser** [comment]
Yup, this is using official Dracula colors: https://github.com/dracula/dracula-theme#color-palette. I'm not saying it isn't flawed though.

So this matches the official color palette:

<img width="529" alt="Screen Shot 2020-11-02 at 1 30 32 PM" src="https://user-images.githubusercontent.com/1055125/97916545-5c4a7d80-1d10-11eb-969b-bb4ae0738c29.png">

I personally prefer something a little more based off the background:

<img width="545" alt="Screen Shot 2020-11-02 at 1 33 38 PM" src="https://user-images.githubusercontent.com/1055125/97916623-7a17e280-1d10-11eb-8030-8528ceb33eb3.png">

**Comment by facelessuser** [comment]
I'm not sure if there is anything I should do here. This scheme is meant to follow the Dracula color scheme as specified. I can maybe see us adding a custom one that takes an opinionated approach with some of the color contrasting...or the whole project can just deviate with an opinionated approach...

I mean, I don't have to provide a pure Dracula experience, but this is mainly provided as a modern Sublime color scheme compared to the official one still locked on to the old tmTheme style.

When using classic style, I'm often using a classic style based my spin on the Pro color scheme. Unfortunately, I have not released these:

<img width="832" alt="Text - Classic" src="https://user-images.githubusercontent.com/1055125/98267380-900fe800-1f48-11eb-9849-eeb9ef9b373b.png">

**Comment by rwols** [comment]
> This scheme is meant to follow the Dracula color scheme as specified.

Okay.

**Comment by facelessuser** [comment]
I'm going to leave this open as I decide what I want to do. I generally agree that the selection highlight is a little poorly selected. Originally this was meant to provide a base for the official color scheme to work off of so they could update their old tmTheme file, but they've kind of sat on that issue, and it looks like they are content with the old tmTheme 🤷. I can do whatever I want here, I just need to decide what that is.

**Comment by facelessuser** [comment]
Maybe, at the very least, we can provide some suggested overrides in the readme. That is if we want to ship a pure Dracula color scheme, but provide improvements.

**Comment by rwols** [comment]
Apologies for being brief. My thought was: what does the  community gain by this being a reference implementation of Dracula? Make it your own and improve it I say :)

**Comment by facelessuser** [comment]
That's fair, and what I've been grappling with. I'm already doing that on my private branch. Why not here as well.

**Comment by facelessuser** [comment]
I've decided to add a variant called `Dracula (Alucard)`. I will leave the original `Dracula` unaltered for those who prefer the classic Dracula "proper". And for those who wisha custom variant, they can use the `Alucard` variant. I will update the Merge theme as well to provide an `Alucard` variant theme (one that uses the `Alucard` scheme.

**Comment by facelessuser** [comment]
`Alucard` color scheme and Merge theme are available. I don't really enable line highlights in Merge, but if people do, the `Alucard` Merge variant will use the new line highlight color.
