### ISSUE TITLE
Possible RGB hex incorrect values?

### ISSUE THREAD

**Issue by clach04** [facelessuser/sublime-dracula-scheme#6]
I'm not a Sublime Text user, so it may seem odd I'm posting an issue here ;-)

I was experimenting with https://github.com/facelessuser/coloraide/ and using some of the values from this project as an experiment. (I was wondering about extracting the colors out to transplant them into a different tool.)

I'm curious about the hex comment in line https://github.com/facelessuser/sublime-dracula-scheme/blob/b6ca59dc28ca359bdaad554e5cef7ec541b7cd94/Dracula%20Pro.sublime-color-scheme#L20

extract of that section:

        "background": "hsl(245, 14%, 15%)",                  // #22212c
        "selection": "color(var(background) s(15%) l(30%))",    // #454158
        "comment": "color(var(background) s(25%) l(55%))",      // #7470a9
        "line-highlight": "color(var(background) s(25%) l(25%))",

With some (scrappy) Python code, I get the same (RGB) value for background and comment but NOT selection. I would not be surprised if this is an error on my part 😁 , the other possibilities are:

1. comment incorrect
2. coloraide bug/behavior
3. ?

Here is what I generate:

    background '#22212c'
    selection '#574242'
    comment '#7470a9'
    line_highlight '#7470a9' -- IGNORE, wrong output/script used - focus on selection

And the test code:

    from coloraide import Color  # https://github.com/facelessuser/coloraide
    
    # from https://github.com/facelessuser/sublime-dracula-scheme/blob/master/Dracula%20Pro.sublime-color-scheme
    background_str = "hsl(245, 14%, 15%)"  # #22212c
    #background_str = "color(hsl(245, 14%, 15%) s(15%) l(30%))"  # worth a shot, didn't pan out
    
    background = Color(background_str)
    
    print('background %s' % background)
    print('background %r' % background)
    print('background %r' % (background.to_string()), )
    print('background h %r' % background['h'])
    print('background s %r' % background['s'])
    print('background l %r' % background['l'])
    print('background %r' % (background.convert('srgb').to_string()), )
    #import pdb; pdb.set_trace()
    print('background %r' % (background.convert('srgb').to_string(hex=True)), )
    
    print('')
    
    # from https://github.com/facelessuser/sublime-dracula-scheme/blob/master/Dracula%20Pro.sublime-color-scheme
    # "selection": "color(var(background) s(15%) l(30%))",    // #454158
    # "comment": "color(var(background) s(25%) l(55%))",      // #7470a9
    # "line-highlight": "color(var(background) s(25%) l(25%))",
    
    #selection = background.filter('saturate', 0.15).filter('brightness', 0.30)  # did NOT produce expected result, manually setting/overriding below did
    selection = Color(background)  # assignment, ends up with a reference not a copy/value
    selection['h'] = 0.15
    selection['l'] = 0.30
    print('selection %s' % selection)
    print('selection %r' % selection)
    print('selection %r' % (selection.to_string()), )
    print('selection %r' % (selection.convert('srgb').to_string()), )
    #import pdb; pdb.set_trace()
    print('selection %r' % (selection.convert('srgb').to_string(hex=True)), )
    
    print('')
    
    #comment = background.filter('saturate', 0.25).filter('brightness', 0.55)  # did NOT produce the expected result, manually setting/overriding below did
    comment = Color(background)
    comment['s'] = 0.25
    comment['l'] = 0.55
    print('comment %s' % comment)
    print('comment %r' % comment)
    print('comment %r' % (comment.to_string()), )
    print('comment %r' % (comment.convert('srgb').to_string()), )
    #import pdb; pdb.set_trace()
    print('comment %r' % (comment.convert('srgb').to_string(hex=True)), )
    
    line_highlight = Color(background)
    line_highlight['s'] = 0.25
    line_highlight['l'] = 0.55
    print('line_highlight %s' % line_highlight)
    print('line_highlight %r' % line_highlight)
    print('line_highlight %r' % (line_highlight.to_string()), )
    print('line_highlight %r' % (line_highlight.convert('srgb').to_string()), )
    #import pdb; pdb.set_trace()
    print('line_highlight %r' % (line_highlight.convert('srgb').to_string(hex=True)), )
    
    print('')
    print('background %r' % (background.convert('srgb').to_string(hex=True)), )
    print('selection %r' % (selection.convert('srgb').to_string(hex=True)), )
    print('comment %r' % (comment.convert('srgb').to_string(hex=True)), )
    print('line_highlight %r' % (line_highlight.convert('srgb').to_string(hex=True)), )
    
    
    print('')
    #print('background %r' % dir(background))

Thanks for making this (and https://github.com/facelessuser/coloraide/) available! 🙏

**Comment by clach04** [comment]
I posted old python code 😿 , the line_highlight output is:

    background '#22212c'
    selection '#574242'
    comment '#7470a9'
    line_highlight '#323050'

With the correct H/L percentages applied to line_highlight.

**Comment by facelessuser** [comment]
```css
"background": "hsl(245, 14%, 15%)",                  // #22212c
"selection": "color(hsl(245, 14%, 15%) s(15%) l(30%))",    // #454158
```

Sublime uses the old CSS `colormod` spec which has been abandoned. But basically, the above is simply saying to take the `background` color and set the saturation to 15% and 30%. (If it had a `+` or a `-` in front, it would be increasing/decreasing by a percentage).

It should be noted that at different times, I may have played around with different percentages, so it's possible I forgot to update the comment. The real value is close to the comment, but not exactly the same.

```python
>>> Color('hsl(245, 14%, 15%)').set('s', 0.15).set('l', 0.3).convert('srgb').to_string(hex=True)
'#434158'
```

**Comment by facelessuser** [comment]
Verifying the colors, the rest match.

```py
>>> Color('hsl(245, 14%, 15%)').set('s', 0.15).set('l', 0.30).convert('srgb').to_string(hex=True)
'#434158'
>>> Color('hsl(245, 14%, 15%)').set('s', 0.25).set('l', 0.55).convert('srgb').to_string(hex=True)
'#7470a9'
>>> Color('hsl(245, 14%, 15%)').set('s', 0.25).set('l', 0.25).convert('srgb').to_string(hex=True)
'#323050'
```

I've updated the comment on main to show `#434158` for selections.

**Comment by facelessuser** [comment]
In short:

1. Comment was only slightly incorrect.
2. Coloraide does not have a bug.

I think you were assuming that applying the saturation and brightness is filter is what we were doing in this theme, but that is not the case. That is why your value differs as `#574242`, which is not correct.

Closing as question has been answered and comment corrected on main.

**Comment by clach04** [comment]
Thanks @facelessuser for the quick response. This was 100% user error, I somehow got a H instead of an S in one line of the code, 

    selection['h'] = 0.15  # supposed to be an 's'!

really sorry for wasting your time, thanks again I'm all set now.
